---
- name: make a build dir
  file: state=directory name=/root/apache2-php5-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/apache2-php5-dockerized/Dockerfile

- name: put apache2.rb
  template: src=apache2.rb dest=/root/apache2-php5-dockerized/apache2.rb

- name: put mpm_prefork.conf
  template: src=mpm_prefork.conf dest=/root/apache2-php5-dockerized/mpm_prefork.conf

- name: put 000-default.conf
  template: src=000-default.conf dest=/root/apache2-php5-dockerized/000-default.conf

- name: build a Docker image for Apache2 and PHP5
  command: docker build -t gitinsky/apache2-php5:0.1.3 --rm /root/apache2-php5-dockerized
